"""Macro provider registry."""

from kronos_fincept.macro.providers.base import MacroProvider, MacroProviderError, MacroProviderUnavailable
from kronos_fincept.macro.providers.digital_oracle import (
    BisProvider,
    CMEFedWatchProvider,
    CftcCotProvider,
    CoinGeckoProvider,
    CurrencyProvider,
    DBnomicsProvider,
    DeribitProvider,
    EdgarProvider,
    FearGreedProvider,
    KalshiProvider,
    PolymarketProvider,
    StooqProvider,
    USTreasuryProvider,
    WebSearchProvider,
    WorldBankProvider,
    YFinanceProvider,
    YahooPriceProvider,
    create_default_providers,
)

__all__ = [
    "BisProvider",
    "CMEFedWatchProvider",
    "CftcCotProvider",
    "CoinGeckoProvider",
    "CurrencyProvider",
    "DBnomicsProvider",
    "DeribitProvider",
    "EdgarProvider",
    "FearGreedProvider",
    "KalshiProvider",
    "MacroProvider",
    "MacroProviderError",
    "MacroProviderUnavailable",
    "PolymarketProvider",
    "StooqProvider",
    "USTreasuryProvider",
    "WebSearchProvider",
    "WorldBankProvider",
    "YFinanceProvider",
    "YahooPriceProvider",
    "create_default_providers",
]
